name = "UrbanTethysChloris"
uuid = "8ae36e77-b357-5cab-a873-ceeadc1a5254"
authors = ["Hugo Solleder <hugo.solleder@epfl.ch>"]
version = "0.12.0"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
LeastSquaresOptim = "0fc2ff8b-aaa3-5acd-a817-1944a5e08891"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TethysChlorisCore = "c22758e7-e854-5bdb-8df2-7602c47a9d98"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[sources]
TethysChlorisCore = {rev = "feat-allow-multiparametric-composite", url = "https://github.com/EPFL-ENAC/TethysChlorisCore.jl"}

[compat]
ADTypes = "1.14.0"
ConstructionBase = "1.6.0"
Dates = "1.11.0"
LeastSquaresOptim = "0.8.7"
LinearAlgebra = "1.11.0"
MAT = "0.10"
NCDatasets = "0.14"
NaNMath = "1.1.3"
OrdinaryDiffEqRosenbrock = "1.10.0"
Roots = "2.2.7"
StaticArrays = "1.9.13"
Statistics = "1.11.1"
TethysChlorisCore = "0.1.3"
YAML = "0.4"
julia = "1.11"
