[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
UrbanTethysChloris = "8ae36e77-b357-5cab-a873-ceeadc1a5254"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
